### PR TITLE
#11117: Fixed issue w\ load of Tag field in contentlets

### PR DESCRIPTION
**Pull request by agomez-dotcms**

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

**Comment by wezell** [comment]
Wait, don't merge this.  I would ask @jtesser or @joseorsini.  I am not sure tags should be added to the content map after 3.5... I am not sure, but I believe the right solution is the call the tagapi and load them up.  Please confirm.

**Comment by joseorsini** [comment]
Unless something has changed recently, the Content Map already calls the TagAPI for retrieving tags associated to a content. 

https://github.com/dotCMS/core/blob/master-4.1/dotCMS/src/main/java/com/dotmarketing/viewtools/content/ContentMap.java#L214 

We never index tags values, they're just pulled from Cache or DB (if necessary) since they are not part of the actual contentlet object in DB.

**Comment by joseorsini** [comment]
Also this needs to be reviewed closely on reported customer. We would need to see if the tags are stored on the right place and not on the contentlet object itself, and after applying the fix, we need to check if they're still stored on tag table (and relationships are created on tag_inode) or otherwise.

**Comment by jgambarios** [comment]
Closed and moved to https://github.com/dotCMS/core/pull/11256

**Pull request closed without merging**
