### PR TITLE
Including '|token' to obfuscation regexp

### PR DESCRIPTION
**Pull request by victoralfaro-dotcms**

### CODE REVIEW

**Review by wezell — APPROVED** [review]
good

**Review by wezell — CHANGES_REQUESTED** [review]
token needs to go before /gi.  Run this by @fabrizzio-dotCMS

**Review by wezell — APPROVED** [review]
yup

**Comment by fabrizzio-dotCMS** [comment]
> token needs to go before /gi. Run this by @fabrizzio-dotCMS

@wezell in the first round of QA the last token wasn't getting matched. That's why I changed it.  Also, The "i" modifier wasn't recognized I added a Pattern.CASE_INSENSITIVE to match them in different cases

**Pull request closed without merging**
