### PR TITLE
Card 802 include related tags when pushing content

### PR DESCRIPTION
**Pull request by dsilvam**

### CODE REVIEW

**Comment by dotcmsCodeReview** [comment]
@Daniel - a specific question for you.  How do we handle the case on card
748 in particular?

**Comment by brentgriffin** [comment]
@dotcmsCodeReview - this is a prerequisite to card 748 - pushing of tags were broken - this fix is for card 802

**Comment by dsilvam** [comment]
@dotcmsCodeReview - we do the following:

we do that by first asking if there is a local tag with the same tagName and host, and if so, we use that one, and if Not, we create a new one with that tagName and host. All of this takes place in the following method:  https://github.com/dotCMS/enterprise-2.x/pull/345/files#diff-adb3fde76a8759f53f2e30602feed696R443

**Comment by wezell** [comment]
So in authoring and prod, we can have a tag with the same tagname, same
taghost but different inodes?  I don't know if this will cause issues or if
this is ok, just asking.

**Comment by dsilvam** [comment]
Yes we can have a tag with same (tagname,host) but different inode in auth and prod.

**Comment by dotcmsCodeReview** [comment]
So when this happens - what happens when I push a bunch of tags (with no
reference to content).  Or do we not push tags unless they are part of
content?

**Comment by dsilvam** [comment]
We do not push tags in isolation

**Pull request merged**
