### PR TITLE
Fixed autocomplete as dropdown and multiple options

### LINKED ISSUE #27421: Design System: Autocomplete component is not responsive when setting multiple as true
### Parent Issue

_No response_

### Problem Statement

The autocomplete component is not re-ordering the content when it has the multiple input set as true and making the component smaller that it's content

## Screenshot
See how tags field is broke in responsive mode
Screenshot 2024-01-24 at 2 19 08 PM

You can also see this issue in storybook.

### Acceptance Criteria

* Autocomplete component should be responsive and not break

### dotCMS Version

`master - latest`

### Proposed Objective

User Experience

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

_No response_

### Assumptions & Initiation Needs

_No response_

### Quality Assurance Notes & Workarounds

_No response_

### Sub-Tasks & Estimates

_No response_

### PR DESCRIPTION
**Pull request by KevinDavilaDotCMS**
### Proposed Changes
* Updated autocomplete styles as dropdown

Showcase:

https://github.com/dotCMS/core/assets/144152756/27213ba3-c978-4fb5-bdaa-42f81eb29616

### CODE REVIEW

**Comment by zJaaal** [comment]
it's kinda weird that in edit content, it creates another line below the items event if there's no items, take a look at that

**Comment by KevinDavilaDotCMS** [comment]
> In the video It's kinda weird that in edit content, it creates another line below the items even if there's no items, take a look at that

I think you are referring to the blue line that surrounds the edge, that is its focus state, it seems to me that this is how it should be since I have not modified that behavior

**Comment by zJaaal** [comment]
> > In the video It's kinda weird that in edit content, it creates another line below the items even if there's no items, take a look at that
> 
> I think you are referring to the blue line that surrounds the edge, that is its focus state, it seems to me that this is how it should be since I have not modified that behavior

Sorry I should have used an screenshot for clarity, my bad.

This is what I refer to.

Screenshot 2024-02-06 at 5 08 01 PM

**Comment by KevinDavilaDotCMS** [comment]
> > > In the video It's kinda weird that in edit content, it creates another line below the items even if there's no items, take a look at that
> > 
> > 
> > I think you are referring to the blue line that surrounds the edge, that is its focus state, it seems to me that this is how it should be since I have not modified that behavior
> 
> Sorry I should have used an screenshot for clarity, my bad.
> 
> This is what I refer to.
> 
> Screenshot 2024-02-06 at 5 08 01 PM

Don't worry! I that responsive case, that white space is necessary because that is where the input is

**Review by zJaaal — APPROVED** [review]

**Review by hmoreras — APPROVED** [review]

**Review by oidacra — APPROVED** [review]

**Pull request merged**
