### PR TITLE
dotCMS/core#23313 Contextual options are not correct

### PR DESCRIPTION
**Pull request by zulqarnainvd**
### Proposed Changes
* Add Contextual menu option according to container status.

### Checklist
- [x] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

### CODE REVIEW

**Comment by fmontes** [comment]
The "Archived" state should only show:

- Unarchive
- Delete

**Comment by fmontes** [comment]
The "Archived" state should ONLY show:

- Unarchive
- Delete

**Comment by zulqarnainvd** [comment]
@fmontes I updated the archived container options.

**Review by fmontes — CHANGES_REQUESTED** [review]
The archive state options should only be "Delete" and "Publish"

**Pull request merged**
