### PR TITLE
Runing test

### PR DESCRIPTION
**Pull request by freddyucv**
I am fixing the DependencyBundleTest, this test fail sometimes with this PR I am fixing several cases when they fail but it still is failing sometimes with a relationships issue (I am going to sent another PR later)

### CODE REVIEW

**Review by nollymar — COMMENTED** [review]
I know this [test](https://raw.githack.com/dotCMS/test-results/Fixing-DependencyBundler-test/projects/core/current/integration/mssql/reports/html/classes/com.dotcms.enterprise.publishing.remote.bundler.DependencyBundlerTest.html#addAssetInBundle:%20Folder%20with%20third%20party) wasn't fixed, but it is failing in MSSQL

**Comment by freddyucv** [comment]
> I know this [test](https://raw.githack.com/dotCMS/test-results/Fixing-DependencyBundler-test/projects/core/current/integration/mssql/reports/html/classes/com.dotcms.enterprise.publishing.remote.bundler.DependencyBundlerTest.html#addAssetInBundle:%20Folder%20with%20third%20party) wasn't fixed, but it is failing in MSSQL



> I know this [test](https://raw.githack.com/dotCMS/test-results/Fixing-DependencyBundler-test/projects/core/current/integration/mssql/reports/html/classes/com.dotcms.enterprise.publishing.remote.bundler.DependencyBundlerTest.html#addAssetInBundle:%20Folder%20with%20third%20party) wasn't fixed, but it is failing in MSSQL

**Comment by freddyucv** [comment]
> I know this [test](https://raw.githack.com/dotCMS/test-results/Fixing-DependencyBundler-test/projects/core/current/integration/mssql/reports/html/classes/com.dotcms.enterprise.publishing.remote.bundler.DependencyBundlerTest.html#addAssetInBundle:%20Folder%20with%20third%20party) wasn't fixed, but it is failing in MSSQL

This is not really about mysql, theses test are failing sometimes for different reasons and I am fixing several of the cause with this PR

**Review by nollymar — APPROVED** [review]

**Review by victoralfaro-dotcms — APPROVED** [review]
LGTM

**Pull request merged**
