### PR TITLE
Issue 8900 backport security improvements

### PR DESCRIPTION
**Pull request by oarrietadotcms**

### CODE REVIEW

**Comment by brentgriffin** [comment]
In TailLogServlet.java we dropped a try/catch block.  Was that intentional?  If so, what was the rationale?

**Comment by oarrietadotcms** [comment]
After some javadoc research and code tests, the try/catch block is not necessary. 

The only exception this lines can throw is NPE, I believe. https://gist.github.com/oarrietadotcms/151ccf4622d9228ba04eaccb8327cb90

getCanonicalPath can throw IOException but it will thrown by the method and logged in the localhost.log under tomcat/logs. In that case the UI will show an 500 error like this:

screen shot 2016-04-19 at 7 45 03 am

**Comment by dsilvam** [comment]
guys but we shouldn't be returning a 500 (caused by a NPE) in case the user does not send the "fileName" parameter. For example a call like this to the servlet: http://localhost:8080/dotTailLogServlet (no fileName param) returns a 500. That shouldn't be the case.

**Comment by brentgriffin** [comment]
Daniel, good catch - please create a github issue for this.

**Pull request merged**
