### PR TITLE
Fix #25660: Block Editor Add Support for H4 H5 H6 Headlines

### LINKED ISSUE #25660: Add support for h4, h5, h6 headlines in Block Editor
### Parent Issue

_No response_

### User Story

We have different support requests to offer h4,h5, and h6 headlines in Block Editor

### Acceptance Criteria

Block Editor should have h4, h5, h6 blocks so customers can add those headlines.

### Proposed Objective

Customer Support

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Ticket: https://dotcms.zendesk.com/agent/tickets/112593

Slack: https://dotcms.slack.com/archives/C028Z3R2D/p1673979176428059

### Assumptions & Initiation Needs

_No response_

### Quality Assurance Notes & Workarounds

_No response_

### Sub-Tasks & Estimates

_No response_

### PR DESCRIPTION
**Pull request by zJaaal**
### Summary
🎨🆕♻️

This pull request adds support for `h4`, `h5`, and `h6` headings in the `dot-block-editor` component and its related files. It updates the bubble menu plugin, the styles, the icons, and the suggestions menu to handle the new heading levels.

> _Sing, O Muse, of the skillful coder who enhanced the editor_
> _With more headings for the content blocks, like a wise builder_
> _Who adds more stories to a tower, reaching for the sky_
> _And adorned the bubble menu with icons, like a painter who beautifies_

### Walkthrough
*  Add styles for h5 and h6 headings in `dot-block-editor.component.scss` ([link](https://github.com/dotCMS/core/pull/25713/files?diff=unified&w=0#diff-efec6605da72e38b58ecc3fecc2b887e97b1c15c6cf4b539571dde81b1e47980L111-R124))
*  Add methods for applying h4, h5, and h6 headings in `dot-bubble-menu.plugin.ts` ([link](https://github.com/dotCMS/core/pull/25713/files?diff=unified&w=0#diff-c8d4bb53e36d994727c35eba8571ce71e300c27447a472e866cc6c01be20b101R442-R450))
*  Add icons for h4, h5, and h6 headings in `suggestion-icons.ts` ([link](https://github.com/dotCMS/core/pull/25713/files?diff=unified&w=0#diff-7d79170dd0e471f4d331f1c06a607df33d91a9596c65fed432126be686071f39L6-R9))
*  Add menu items for h4, h5, and h6 headings in `suggestion.utils.ts` ([link](https://github.com/dotCMS/core/pull/25713/files?diff=unified&w=0#diff-8189a782af79a6de865f15b8d9f96efa172113e2d04c33753f771ada3ccabd5eL19-R24))
*  Separate imports from class declaration in `dot-bubble-menu.plugin.ts` ([link](https://github.com/dotCMS/core/pull/25713/files?diff=unified&w=0#diff-c8d4bb53e36d994727c35eba8571ce71e300c27447a472e866cc6c01be20b101R422))

### Screenshot
https://github.com/dotCMS/core/assets/63567962/4c324b41-38c3-40a7-8461-442b66295bf5

### CODE REVIEW

**Review by manuelrojas — APPROVED** [review]

**Review by hmoreras — APPROVED** [review]

**Review by rjvelazco — CHANGES_REQUESTED** [review]
Hey @zJaaal, have the new blocks (`headings`) been added to the `Block Editor Fields > Settings > Allow Blocks` configuration?

block-editor-settings

**Comment by zJaaal** [comment]
> Hey @zJaaal, have the new blocks (`headings`) been added to the `Block Editor Fields > Settings > Allow Blocks` configuration?
> 
> block-editor-settings

Yes! Those options are populated using the same model as the Bubble Menu, so whatever you add to that model, will be added to this dropdown as well using.

That occurs right here [suggestions.utils.ts L94](https://github.com/dotCMS/core/pull/25713/files#diff-8189a782af79a6de865f15b8d9f96efa172113e2d04c33753f771ada3ccabd5eR94)

**Review by rjvelazco — APPROVED** [review]

**Comment by hotaru-ritsuki** [comment]
In order to add full support for a feature also changes needs to be done for velocity files in `dotCMS/src/main/webapp/WEB-INF/velocity/static/storyblock` :
1. Create heading4.vtl, heading5.vtl, heading6.vtl
2. Edit render.vtl to add support for h4,h5,h6

**Comment by zJaaal** [comment]
> In order to add full support for a feature there are some additional changes that need to be done for velocity files in `dotCMS/src/main/webapp/WEB-INF/velocity/static/storyblock` :
> 
> 1. Create heading4.vtl, heading5.vtl, heading6.vtl
> 2. Edit render.vtl to add support for h4,h5,h6

Yes! You are right, thanks for the advice!

**Pull request merged**
