### PR TITLE
#17698 currently webdav force lowercase on the file name, now it is n…

### PR DESCRIPTION
**Pull request by jdotcms**
…ot but still unsensitive when search

### CODE REVIEW

**Comment by jdotcms** [comment]
Previously when an asset was upload on weddav the name was convert to lower. Now it is respecting the name as it is, but the search still being insensitive

**Comment by wezell** [comment]
@jdotcms, does this fix the folder case as well?

**Comment by dsilvam** [comment]
What about files? @jdotcms

**Review by erickgonzalez — APPROVED** [review]

**Comment by jdotcms** [comment]
files yes, folders I am not sure will try

**Comment by jdotcms** [comment]
I have push a fix and now both (file and folder) are case insensitive

**Review by dsilvam — APPROVED** [review]

**Review by jgambarios — APPROVED** [review]

**Comment by jgambarios** [comment]
Closed as the fixes included here were applied in https://github.com/dotCMS/core/pull/17802

**Pull request closed without merging**
