### PR TITLE
Issue 16939 Restore clean/clear field value functionality when deleting a field

### PR DESCRIPTION
**Pull request by dsilvam**

### CODE REVIEW

**Review by nollymar — APPROVED** [review]

**Comment by dsilvam** [comment]
This is actually to fix https://github.com/dotCMS/core/issues/16939

**Comment by wezell** [comment]
Does this break the transactions? If not then I approve.

**Comment by dsilvam** [comment]
@wezell this do not. This just restores the execution of the job.

**Comment by wezell** [comment]
We need to merge this with the changes here and validate:
#17593

**Review by erickgonzalez — APPROVED** [review]

**Pull request merged**
