### PR TITLE
#20457 fix contentlet metaData attribute via vtl

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
This fixes an issue accessing metadata from vtl files
like this: 

```
#foreach($file in $dotcontent.pull("+contentType:FileAsset +metaData:image/jpeg",2,"modDate desc"))
   
    <h3>MetaData:</h3>
    <p>$file.metaData</p>
  
    <p>Content type: $file.metaData.contentType</p>
    <p>File Size: $file.metaData.fileSize</p>
#end

```

### CODE REVIEW

**Review by nollymar — COMMENTED** [review]
I think a test can be implemented here with an assertion like:

```
   Assert.true(contentlet.get("metaData") instanceOf Map)
```

And validate that some fields from this map are retrieved.

**Review by jdotcms — APPROVED** [review]

**Comment by fabrizzio-dotCMS** [comment]
> I think a test can be implemented here with an assertion like:
> 
> ```
>    Assert.true(contentlet.get("metaData") instanceOf Map)
> ```
> 
> And validate that some fields from this map are retrieved.

**Comment by fabrizzio-dotCMS** [comment]
> I think a test can be implemented here with an assertion like:
> 
> ```
>    Assert.true(contentlet.get("metaData") instanceOf Map)
> ```
> 
> And validate that some fields from this map are retrieved.

done.

**Review by wezell — CHANGES_REQUESTED** [review]
Keep in mind that normal key/values are user order-able and when displayed should maintain the order they have set in the backend (you can drag and drop them to order)- which is why we were using a LinkedHashMap

**Comment by wezell** [comment]
Also, using the scripting API, it would be easy to write a Postman test for this:

**Comment by fabrizzio-dotCMS** [comment]
> Keep in mind that normal key/values are user order-able and when displayed should maintain the order they have set in the backend (you can drag and drop them to order)- which is why we were using a LinkedHashMap

thought we were gonna remove the **metaData** from the FileAsset Content-type. It will be no longer a KeyValue. 
However, I'll use a `LinkedHashMap`

**Comment by fabrizzio-dotCMS** [comment]
Closed in favor of https://github.com/dotCMS/core/pull/20466

**Pull request closed without merging**
