### PR TITLE
dotCMS/core#23606 Containers: Match "Add variable" UI

### PR DESCRIPTION
**Pull request by zulqarnainvd**
### Proposed Changes
* Match Figma Design of Add Variable Modal and update test case
### Checklist
- [x] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
** any additional useful context or info **

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **
image

image

### CODE REVIEW

**Review by fmontes — APPROVED** [review]
This code looks good to me, but I am uncertain if the screenshot matches the design.

For example, the "Add" button looks like the "flex" is making it taller.

Also the font size I can't tell from the screenshot, but looks bigger.

**Comment by fmontes** [comment]
@zulqarnainvd Please check my comment above.

**Comment by zulqarnainvd** [comment]
@fmontes noted

**Comment by zulqarnainvd** [comment]
Please check
image

**Comment by zulqarnainvd** [comment]
@rjvelazco @hmoreras Guys, Please review the video if you didn't get what I fixed on this PR.
[screen-capture (2).webm](https://user-images.githubusercontent.com/113915849/208710937-286b659e-af73-468f-a68a-bd296945d326.webm)

**Review by rjvelazco — APPROVED** [review]

**Review by hmoreras — APPROVED** [review]

**Pull request merged**
