### PR TITLE
Update ApiToken_Resource.postman_collection.json

### LINKED ISSUE #27161: ApiToken_Resource.postman_collection

### LINKED ISSUE #27209: ApiToken_Resource.postman_collection.json

### PR DESCRIPTION
**Pull request by rsh1k**
### Proposed Changes

Added the following postman tests:

* Check for expiry date. Expiry date should be in future. 
* Check if token ID is unique or not.
* Check the JWT format
* Check for rate limit

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

**Review by AndreyDotcms — APPROVED** [review]

**Comment by mbiuki** [comment]
@bryanboza - is this ready to merge?

**Review by nollymar — CHANGES_REQUESTED** [review]
The postman test is broken. Please fix it

**Comment by rashik1144** [comment]
> The postman test is broken. Please fix it

@nollymar This is working as expected. What are you referring to? 
image
image
image

**Comment by mbiuki** [comment]
@rashik1144 could you please sync up with @nollymar to check the test alignment - also why there are two issues attached to this PR?

https://github.com/dotCMS/core/issues/27209
 
https://github.com/dotCMS/core/issues/27161

**Comment by mbiuki** [comment]
So it looks like Steve was trying to sample https://github.com/dotCMS/core/issues/27161 and this can be removed and deleted. @nollymar please help @rashik1144 to close https://github.com/dotCMS/core/issues/27161, thanks

**Review by nollymar — APPROVED** [review]

**Pull request merged**
