### PR TITLE
#7883 - added separate null check

### PR DESCRIPTION
**Pull request by austindlawless**
Fix for issue #7883

### CODE REVIEW

**Comment by jtesser** [comment]
hey @austindlawless Have you signed our contributor agreement? I don't think so.  We cannot merge code without this being signed.  Would you like me to send to you?

**Comment by austindlawless** [comment]
I did sign it and send it to you. 

Austin Lawless
817-456-9137

**Comment by jtesser** [comment]
yea sorry :-p

On Thu, Jun 25, 2015 at 9:21 AM, Austin Lawless <notifications@github.com>
wrote:

> I did sign it and send it to you.
>
> Austin Lawless
> 817-456-9137
>
> > On Jun 25, 2015, at 7:27 AM, Jason Tesser <notifications@github.com>
> wrote:
> >
> > hey @austindlawless Have you signed our contributor agreement? I don't
> think so. We cannot merge code without this being signed. Would you like me
> to send to you?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/pull/7884#issuecomment-115255962>.
>



-- 

3250 Mary Street
Suite 405
Miami, FL 33133
Main: 305-900-2001 | Direct: 305.209.8104

jason.tesser@dotcms.com <jason@dotcms.com> | dotcms.com
<http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by austindlawless** [comment]
No worries.

Hopefully I did the pull request right. Let me know if I need to do anything differently in the future. 

Austin Lawless
817-456-9137

**Comment by austindlawless** [comment]
Is this going to get merged?

**Pull request merged**
