### PR TITLE
Add your-account-is-not-active to Language.properties

### PR DESCRIPTION
**Pull request by jinta**
### Proposed Changes
* Add your-account-is-not-active to Language.properties

### CODE REVIEW

**Review by wezell — APPROVED** [review]

**Review by wezell — CHANGES_REQUESTED** [review]
@jinta :

Can you please enter a comment in your PR saying that you agree to the dotCMS Contributor's License Agreement found here:

https://gist.github.com/wezell/85ef45298c48494b90d92755b583acb3

**Comment by jinta** [comment]
I agree to the dotCMS Contributor's License Agreement.

Thanks for the approval

**Review by wezell — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]

**Comment by jinta** [comment]
Bump because stale label

**Comment by jinta** [comment]
bump

**Pull request merged**
