### PR TITLE
Incorporate velocity 841

### PR DESCRIPTION
**Pull request by wezell**
screen shot 2017-04-05 at 11 15 49 am

### CODE REVIEW

**Comment by wezell** [comment]
Hold on this, found an issue

**Comment by wezell** [comment]
ok, false alarm, it was trying to de-serialize a velocity resource that was serialized using the old code.

**Review by dsilvam — APPROVED** [review]

**Comment by jgambarios** [comment]
Closed and moved to https://github.com/dotCMS/core/pull/11254

**Comment by john-thomas-dotcms** [comment]
Are there any documentation (or change log) updates needed for this, or do the changes all happen invisibly in the background?

**Comment by wezell** [comment]
The new velocity work changes the cache regions we use for velocity. We need to document that.

**Pull request closed without merging**
