### PR TITLE
Issue 8238 

### PR DESCRIPTION
**Pull request by joseorsini**
keep session alive for notifications api call (depending on config)

### CODE REVIEW

**Comment by joseorsini** [comment]
Tested as backported hotfix in 3.2.3.

If KEEP_SESSION_ALIVE is set to true, checkNotifications() is called every 5 seconds. 
If it's set to false, checkNotifications() is calle 5 seconds after page load. It's not called again until the browser is refreshed.

**Comment by jtesser** [comment]
@joseorsini I am going to close this one because I think you went with the other fix not this one right?

**Comment by joseorsini** [comment]
You would need to merge the commit from Will and the other one I committed in the other pull request.

**Comment by jtesser** [comment]
@joseorsini r u talking about will's commit on this pull request?

**Comment by joseorsini** [comment]
Yes. The fix is splitted in two. First commit is from Will, the nav_sub_inc.jsp requires a way to control the hits to the Notifications REST API if Keep session alive property is set to false. The other commit (which is in a separate pull request) is for bottom_portal_inc.jsp, where we should control how much time a session should be alive depending on the same config property.

**Pull request merged**
