### PR TITLE
Card 762 delete old assets

### PR DESCRIPTION
**Pull request by oarrietadotcms**

### CODE REVIEW

**Comment by wezell** [comment]
I would be careful here, the in (x,x,x,x) clause can blow up if there are too many containers.  You should build a list of 100 and delete them and iterate over it again and again.

**Comment by oarrietadotcms** [comment]
Thanks, I will do the change.

**Comment by dsilvam** [comment]
why not using a join between the two tables?

**Comment by wezell** [comment]
Daniel's idea is the right solution here, rather than nesting queries.

**Comment by wezell** [comment]
I think iterating over 100 at a time is ok for now, if the logic works on large datasets. @QA can we test against some old client data?

Here is an example of how to do delete queries like this without the nested select - I don't know about other DBs but this works for me on mysql.  From my understanding, this logic is almost always going to be more performant and optimized

```
delete contentlet from contentlet left join contentlet_version_info cvi1 on (cvi1.working_inode = contentlet.inode or cvi1.live_inode = contentlet.inode)
where  contentlet.mod_date < '2016-01-01' 
and cvi1.identifier is null ;

delete inode from inode left join contentlet_version_info cvi1 on (cvi1.working_inode = inode.inode or cvi1.live_inode = inode.inode)
where  inode.idate < '2016-01-01' 
and cvi1.identifier is null 
and inode.type = 'contentlet';
```

**Pull request merged**
