### PR TITLE
#10049 add improvements for UTF-8 file encoding

### PR DESCRIPTION
**Pull request by joseorsini**
Tested on backported fix to 3.6.0 on Postgres and MySQL:

1. Tested clean install. Works OK.
2. Tested backing up data/assets from Maintenance portlet. Works OK.
3. Tested with backed up data as clean install (renamed backup to starter.zip). Works OK.

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]
Perfect

**Review by dsilvam — APPROVED** [review]

**Comment by joseorsini** [comment]
@jdotcms please commit your updates on ViewCMSMaintenanceAction class that we were testing with customer's data

**Comment by jgambarios** [comment]
@jdotcms @joseorsini there is something missing here or the pull is ready?

**Comment by joseorsini** [comment]
@jgambarios there is a pending fix that @jdotcms implemented and tested.

**Comment by jgambarios** [comment]
@joseorsini can I close this pull request, it is ready as it is right now?, it is marked for 3.6.1 and don't see the pending commits we talked about.

**Comment by joseorsini** [comment]
feel free to close it.

**Pull request closed without merging**
