### PR TITLE
fix: commit hook does not work in Windows WSL ubuntu (#29180)

### LINKED ISSUE #29180: commit hook does not work in Windows WSL (ubuntu)
@gavriella-dotcms is currently working on a Windows machine. 

We only support Windows currently in its Linux layer WSL a version of Ubuntu.   The commit hook has issues that make it not cross-compatible and only currently works on a Mac.

Using AI we were able to create a version that works, it just needs checking that it still works on Mac also

### PR DESCRIPTION
**Pull request by spbolton**
### Proposed Changes
* Fixup order of install operations
* set path for yarn and node
* ensure bash is used for shell consistency.

notes

* The same behavior that occurs on Windows WSL also occurs and can be tested in ubuntu:20.04

docker run --rm -it ubuntu:20.04 /bin/bash

Note the clone and build will take longer as it is building clean without any existing downloaded dependencies.

apt-get update
apt-get install -y curl zip unzip git vi
curl -s "https://get.sdkman.io" | bash
source "/root/.sdkman/bin/sdkman-init.sh"
git clone https://github.com/dotCMS/core.git
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
cd core
./mvn clean install -DskipTests -Ddocker.skip=true
sdk env install
(make a test chage to a file to commit we will not be pushing this commit)
git status 
git add {my changed file}
git commit -m "test change"

Check progress if it succeeds then you can revert the test commit for further changes leaving the changed files in the local index with
git reset HEAD~1

Note: 
* Unless an initial build is run then the husky commit hook is not installed and will allow the commit without running at all. 

### Checklist
- [ ] Tests
- [ ] Translations
- [ ] Security Implications Contemplated (add notes if applicable)

### Additional Info
This PR resolves #29180 (commit hook does not work in Windows WSL ubuntu).

### Screenshots
Original             |  Updated
:-------------------------:|:-------------------------:
** original screenshot **  |  ** updated screenshot **

This PR fixes: #29180

### CODE REVIEW

**Review by jdotcms — APPROVED** [review]

**Comment by jdcmsd** [comment]
Quick note on the build steps given above, for anyone else following them.

A couple of typos:
`vi` -> `vim`
`mvn` -> `mvnw`

Also, add the following steps.

After `source "/root/.sdkman/bin/sdkman-init.sh"`, do these:
```
sdk install java 21.0.4-ms
sdk use java 21.0.4-ms
apt-get install -y chromium-bsu 
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
source ~/.bashrc
```

May also require `apt-get install -y yarn`.

After these steps, the build process should succeed.

(I didn't realize it until later, but it is also possible that switching the order of two commands may also cover the above. Tht is, put `sdk env install` before `./mvn clean install -DskipTests -Ddocker.skip=true`.)

The build is successful after that.

That said, still landing at the following error during commit:

```
root@6573fb2110da:/core# git commit -m "test"
core-web/.husky/pre-commit: 146: Syntax error: "(" unexpected (expecting "fi")
husky - pre-commit hook exited with code 2 (error)
root@6573fb2110da:/core#
```

**Comment by spbolton** [comment]
@jdcmsd The error you saw was the windows wsl error before this commit.   The instructions are to test master against this.   To test the fix you would have to do a "git checkout issue-29180-commit-hook-does-not-work-in-windows-wsl-ubuntu" after the clone to be using this branches code and the fix.

**Comment by jdcmsd** [comment]
@spbolton ah, ok. I think in this case some finer point of git manipulation is lost on me; the attempted commit was to the branch, but I suspect I'm overlooking something in the "after the clone to be using this branches code and the fix" bit. I.e., should I be making a new branch from this branch? I notice IntelliJ is able to immediately associate the branch with this PR, so maybe my attempts to commit here are somehow suspect.

(Or is there another step entirely that I'm not grokking?)

**Comment by jdcmsd** [comment]
Disregard last comment; I just had a brainfart and mixed up where I was supposed to be working. 

Can confirm now that the commit succeeds!

Sending approval accordingly.

**Review by jdcmsd — APPROVED** [review]
Confirming successful operation!

**Pull request merged**
