### PR TITLE
#22978 perf improvement

### PR DESCRIPTION
**Pull request by fabrizzio-dotCMS**
### Proposed Changes
* there's a faster way to reset the contents of StringBuilder

### CODE REVIEW

**Review by dsilvam — APPROVED** [review]

**Comment by fabrizzio-dotCMS** [comment]
@wezell can I get your blessing on this PR?

**Comment by fabrizzio-dotCMS** [comment]
After reading this: 

`Note: After looking at the implementation of .delete and .setLength, .delete sets length = 0, and .setLength sets every thing to '\0' So you may get a little win with .delete`

from https://stackoverflow.com/questions/7168881/what-is-more-efficient-stringbuffer-new-or-delete0-sb-length
Im not so sure anymore

**Comment by wezell** [comment]
You don't think the sync on the write is néeded?  Can something be writing while the value is being read?

**Comment by fabrizzio-dotCMS** [comment]
> 

Well yes there can be new lines while we read and clean but I thought one single synch would suffice 

> You don't think the sync on the write is needed? Can something be written while the value is being read?

yeah, I guess there can be new content while we get it sent on its way out to the client side. True.

I'll put another sync block

**Pull request closed without merging**
