### PR TITLE
#19096 now can not delete a template if it is not first archive

### PR DESCRIPTION
**Pull request by jdotcms**
When a template is deleted, must be archive to proceed

### CODE REVIEW

**Review by erickgonzalez — COMMENTED** [review]
test?

**Comment by jdotcms** [comment]
> test?
Curl test already done

**Review by erickgonzalez — APPROVED** [review]

**Comment by wezell** [comment]
Do we have a "doNotValidate"?  We need to make sure deleting hosts with templates in use still work.

**Review by dsilvam — APPROVED** [review]

**Comment by dsilvam** [comment]
@jdotcms  @wezell , I am also wondering if this validation should be done at "java api" level instead of at REST Level

**Comment by wezell** [comment]
> @jdotcms  @wezell , I am also wondering if this validation should be done at "java api" level instead of at REST Level
> 

Not sure, though I would guess not. I would hate for a change like that to break other things

**Pull request merged**
