### PR TITLE
813 add rules successfully fired to user session

### PR DESCRIPTION
**Pull request by freddyucv**

### CODE REVIEW

**Comment by wezell** [comment]
I think we talked about it being a List or a LinkedHashSet?  We will need
to see the order that fired.

On Mon, Mar 28, 2016 at 11:44 AM, Jason Tesser <notifications@github.com>
wrote:

> Merged #8792 <https://github.com/dotCMS/core/pull/8792>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dotCMS/core/pull/8792#event-605364824>
>



-- 






3059 Grand Avenue
Suite 410-B
Miami FL 33133
Main: 305-900-2001 | Direct: 978.294.9429

will@dotcms.com | dotcms.com <http://www.dotcms.com/>

<https://twitter.com/dotcms>  <http://www.linkedin.com/company/dotcms>
<https://plus.google.com/+Dotcms>  <https://www.facebook.com/dotCMS>

**Comment by jtesser** [comment]
Yes @wezell u r right.

**Comment by jtesser** [comment]
I was thinking that was a different card but yea

**Comment by jtesser** [comment]
we decided an arraylist NOT a set so the same value can exist 
a,b,a,d,b

**Pull request merged**
