### PR TITLE
Issue 20203 rework graphql pageapi call

### PR DESCRIPTION
**Pull request by dsilvam**
This reworks the `_map` special GraphQL Field to include the following features:

* Ability to fetch the entire contentlet's map
* Ability to fetch the related content following the same approach of the Content Resource, by providing a `depth` argument with the same behavior.
* Ability to (velocity) render all the renderable fields 

Also includes a postman test for the first level properties. Tests for the rendering and bringing related content abilities were left out for the master version or for late in 21.06 if approval from front-end team is received.

### CODE REVIEW

**Review by erickgonzalez — APPROVED** [review]
Looks good but on a side note: can you look at the graphql tests that are failing for a long time since you are now in that code 😄

**Review by freddyucv — APPROVED** [review]

**Review by jdotcms — COMMENTED** [review]
Good

**Comment by victoralfaro-dotcms** [comment]
Results with just providing `_map` GrpahQL special field:
```
By using JSONLint.com you accept our use of cookies and agree to our privacy policy.
Got it!
JSONJSONLint - The JSON Validator
More Developer Tools
Try the New Pro

"language": {
	"languageId": 1,
	"language": "English",
	"languageCode": "en",
	"country": "United States",
	"countryCode": "US",
	"languageFlag": "en_US",
	"isoCode": "en-us",
	"id": 1
}
1
"contentlets": [{
2
    "_map": {
3
        "myFile": {
4
            "identifier": "8dd88708-c600-4366-8a50-9eec2af9091b",
5
            "parent": "9716b18a-8b2f-44de-8c10-13f886c6f119",
6
            "extension": "jpg",
7
            "isContentlet": true,
8
            "description": "isalnds-french-polynesia",
9
            "__icon__": "jpgIcon",
10
            "mimeType": "image/jpeg",
11
            "statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
12
            "type": "file_asset",
13
            "metaData": {
14
                "path": "c/5/c5ad88f9-31b3-458b-87ed-64f2c1cf82b5/fileAsset/isalnds-french-polynesia.jpg",
15
                "isImage": true,
16
                "modDate": 1621890340000,
17
                "sha256": "6c6658a841c3ae9a60d20143d4de6e320664411a9458b92c787b6201136164e5",
18
                "fileSize": 102816,
19
                "length": 102816,
20
                "name": "isalnds-french-polynesia.jpg",
21
                "width": 780,
22
                "title": "isalnds-french-polynesia.jpg",
23
                "contentType": "image/jpeg",
24
                "height": 520
25
            },
26
            "path": "/images/blogs/",
27
            "size": 102816,
28
            "name": "isalnds-french-polynesia.jpg",
29
            "width": 780,
Validate JSON ClearSupport JSONLint for $2/Month
Results
Error: Parse error on line 1:
"contentlets": [{	"_map": {		"m
-------------^
Expecting 'EOF', '}', ',', ']', got ':'
JSONLint Partners

Check out their products!
About JSONLint Editor
JSONLint is a validator and reformatter for JSON, a lightweight data-interchange format. Copy and paste, directly type, or input a URL in the editor above and let JSONLint tidy and validate your messy JSON code.

What Is JSON?
JSON (pronounced as Jason), stands for "JavaScript Object Notation," is a human-readable and compact solution to represent a complex data structure and facilitate data interchange between systems. It's a widespread data format with a diverse range of applications enabled by its simplicity and semblance to readable text. As such, it's used by most but not all systems for communicating data.

Why Use JSON?
There are several reasons why you should consider using JSON, the key reason being that JSON is independent of your system's programming language, despite being derived from JavaScript. Not only is JSON language-independent, but it also represents data that speaks common elements of many programming languages, effectively making it into a universal data representation understood by all systems.

Other reasons include:

Readability – JSON is human-readable, given proper formatting.
Compactness – JSON data format doesn't use a complete markup structure, unlike XML.
It's easy to analyze into logical syntactic components, especially in JavaScript.
Countless JSON libraries are available for most programming languages.
Proper JSON Format
Using JSON doesn't require any JavaScript knowledge, though having such would only improve your understanding of JSON. And though the knowledge of JavaScript isn't necessary, following specific rules is:

Data is in name/value pairs
Data is separated by commas
Objects are encapsulated within the opening and closing curly brackets
An empty object can be represented by {}
Arrays are encapsulated within opening and closing square brackets
An empty array can be represented by []
A member is represented by a key-value pair, contained in double quotes
Each member should have a unique key within an object structure
The value of a member must be contained in double quotes, if it's a string
Boolean values are represented using the true or false literals in lower case
Number values are represented using double-precision floating-point format and shouldn't have leading zeroes
"Offensive" characters in a string need to be escaped using the backslash character \
Null values are represented by the null literal in lower case
Dates, and similar object types, aren't adequately supported and should be converted to strings
Each member of an object or array value must be followed by a comma, except for the last one
The standard extension for the JSON file is '.json'
The mime type for JSON files is 'application/json'
You can achieve proper JSON formatting by following these simple rules. However, if you're unsure about your code, we suggest using JSONLint Validator.

Why Use JSONLint Validator?
Programming can be challenging, as it requires enormous attention and excellent knowledge of the programming language, even as simple as JSON. Still, writing codeis tricky, and finding an error in JSON code can be a challenging and time-consuming task.

The best way to find and correct errors while simultaneously saving time is to use an online tool such as JSONLint. JSONLint will check the validity of your JSON code, detect and point out line numbers of the code containing errors. It's an excellent way to correct errors without wasting hours finding a missing coma somewhere inside your code.

How Does A JSONLint Validator Work?
JSONLint is an online editor, validator, and reformat tool for JSON, which allows you to directly type your code, copy and paste it, or input a URL containing your code. It will validate your JSON content according to JS standards, informing you of every human-made error, which happens for a multitude of reasons – one of them being the lack of focus.

Using JSONLint, you can quickly find any errors that might've occurred, allowing youto focus more on the rest of your code than on a tiny error itself.

Tips & Tricks
You can directly input a URL into the editor and JSONLint will scrape it for JSON and parse it.
You can provide JSON to lint in the URL if you link to JSONLint with the "json" parameter. Here's an example URL to test.
JSONLint can also be used as a JSON compressor if you add ?reformat=compress to the URL.
Common Errors
Expecting 'STRING' - You probably have an extra comma at the end of your collection. Something like { "a": "b", }
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' - You probably have an extra comma at the end of your list. Something like: ["a", "b", ]
Enclosing your collection keys in quotes. Proper format for a collection is { "key": "value" }
Make sure you follow JSON's syntax properly. For example, always use double quotes, always quotify your keys, and remove all callback functions.
Different Results
If you use a Windows computer you may end up with different results. This is possibly due to the way Windows handles newlines. Essentially, if you have just newline characters (\n) in your JSON and paste it into JSONLint from a Windows computer, it may validate it as valid erroneously since Windows may need a carriage return (\r) as well to detect newlines properly. As a solution, either use direct URL input, or make sure your content's newlines match the architecture your system expects!

Credits
Maintained by CircleCell. Thanks to Douglas Crockford of JSON and JS Lint, and Zach Carter, who built a pure JavaScript implementation. You can download the JSONLint source code on GitHub.

© 2021 JSONLint.com — Advertise Here — Privacy

```
`myFile`, `myImage` and `Language` showed as composed types:
```
"myFile": {
	"identifier": "8dd88708-c600-4366-8a50-9eec2af9091b",
	"parent": "9716b18a-8b2f-44de-8c10-13f886c6f119",
	"extension": "jpg",
	"isContentlet": true,
	"description": "isalnds-french-polynesia",
	"__icon__": "jpgIcon",
	"mimeType": "image/jpeg",
	"statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
	"type": "file_asset",
	"metaData": {
		"path": "c/5/c5ad88f9-31b3-458b-87ed-64f2c1cf82b5/fileAsset/isalnds-french-polynesia.jpg",
		"isImage": true,
		"modDate": 1621890340000,
		"sha256": "6c6658a841c3ae9a60d20143d4de6e320664411a9458b92c787b6201136164e5",
		"fileSize": 102816,
		"length": 102816,
		"name": "isalnds-french-polynesia.jpg",
		"width": 780,
		"title": "isalnds-french-polynesia.jpg",
		"contentType": "image/jpeg",
		"height": 520
	},
	"path": "/images/blogs/",
	"size": 102816,
	"name": "isalnds-french-polynesia.jpg",
	"width": 780,
	"underlyingFileName": "isalnds-french-polynesia.jpg",
	"height": 520
}
```
```
"myImage": {
	"identifier": "4068c24e-4f15-472e-86fc-a57dc785f0c6",
	"parent": "9716b18a-8b2f-44de-8c10-13f886c6f119",
	"extension": "jpg",
	"isContentlet": true,
	"description": "shark-feeding",
	"__icon__": "jpgIcon",
	"mimeType": "image/jpeg",
	"statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
	"type": "file_asset",
	"metaData": {
		"path": "6/1/615cf6c7-a5fb-4c2d-bc0d-f27ec69d9118/fileAsset/shark-feeding.jpg",
		"isImage": true,
		"modDate": 1621890339000,
		"sha256": "03fc29afd486f484b22d5b19408d61bde01314d5164f36f02bacb0d140780065",
		"fileSize": 98885,
		"length": 98885,
		"name": "shark-feeding.jpg",
		"width": 780,
		"title": "shark-feeding.jpg",
		"contentType": "image/jpeg",
		"height": 413
	},
	"path": "/images/blogs/",
	"size": 98885,
	"name": "shark-feeding.jpg",
	"width": 780,
	"underlyingFileName": "shark-feeding.jpg",
	"height": 413
}
```
```
"language": {
	"languageId": 1,
	"language": "English",
	"languageCode": "en",
	"country": "United States",
	"countryCode": "US",
	"languageFlag": "en_US",
	"isoCode": "en-us",
	"id": 1
}
```

**Comment by victoralfaro-dotcms** [comment]
```
`myFile`, `myImage` and `Language` showed as composed types:
```
"myFile": {
	"identifier": "8dd88708-c600-4366-8a50-9eec2af9091b",
	"parent": "9716b18a-8b2f-44de-8c10-13f886c6f119",
	"extension": "jpg",
	"isContentlet": true,
	"description": "isalnds-french-polynesia",
	"__icon__": "jpgIcon",
	"mimeType": "image/jpeg",
	"statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
	"type": "file_asset",
	"metaData": {
		"path": "c/5/c5ad88f9-31b3-458b-87ed-64f2c1cf82b5/fileAsset/isalnds-french-polynesia.jpg",
		"isImage": true,
		"modDate": 1621890340000,
		"sha256": "6c6658a841c3ae9a60d20143d4de6e320664411a9458b92c787b6201136164e5",
		"fileSize": 102816,
		"length": 102816,
		"name": "isalnds-french-polynesia.jpg",
		"width": 780,
		"title": "isalnds-french-polynesia.jpg",
		"contentType": "image/jpeg",
		"height": 520
	},
	"path": "/images/blogs/",
	"size": 102816,
	"name": "isalnds-french-polynesia.jpg",
	"width": 780,
	"underlyingFileName": "isalnds-french-polynesia.jpg",
	"height": 520
}
```
```
"myImage": {
	"identifier": "4068c24e-4f15-472e-86fc-a57dc785f0c6",
	"parent": "9716b18a-8b2f-44de-8c10-13f886c6f119",
	"extension": "jpg",
	"isContentlet": true,
	"description": "shark-feeding",
	"__icon__": "jpgIcon",
	"mimeType": "image/jpeg",
	"statusIcons": "<span class='greyDotIcon' style='opacity:.4'></span><span class='liveIcon'></span>",
	"type": "file_asset",
	"metaData": {
		"path": "6/1/615cf6c7-a5fb-4c2d-bc0d-f27ec69d9118/fileAsset/shark-feeding.jpg",
		"isImage": true,
		"modDate": 1621890339000,
		"sha256": "03fc29afd486f484b22d5b19408d61bde01314d5164f36f02bacb0d140780065",
		"fileSize": 98885,
		"length": 98885,
		"name": "shark-feeding.jpg",
		"width": 780,
		"title": "shark-feeding.jpg",
		"contentType": "image/jpeg",
		"height": 413
	},
	"path": "/images/blogs/",
	"size": 98885,
	"name": "shark-feeding.jpg",
	"width": 780,
	"underlyingFileName": "shark-feeding.jpg",
	"height": 413
}
```
```
"language": {
	"languageId": 1,
	"language": "English",
	"languageCode": "en",
	"country": "United States",
	"countryCode": "US",
	"languageFlag": "en_US",
	"isoCode": "en-us",
	"id": 1
}

**Comment by victoralfaro-dotcms** [comment]
```
With `depth: 0`
```
"author": [
	"f851e34a-d128-408e-a75a-4fa1c33201b8"
]
...
"blogComment": [
	"75e62bcd-294b-4f15-9d37-133c19799a18",
	"23edb4fa-a363-4dfa-b12b-8f3a07415248"
]
```
With `depth: 1`
```
"author": [{
	"publishDate": "2021-06-02 12:38:07.685",
	"language": {
		"languageId": 1,
		"language": "English",
		"languageCode": "en",
		"country": "United States",
		"countryCode": "US",
		"languageFlag": "en_US",
		"isoCode": "en-us",
		"id": 1
	},
	"inode": "baf596fa-7592-4336-8674-b2ef6d8af748",
	"profilePhoto": {
		"modDate": 1621890340000,
		"sha256": "b1aa20d9c5420987d2503db6eea29074f478e6b63d73dbf6f48f8db39448303b",
		"mime": "image/jpeg",
		"title": "john-smith.jpg",
		"versionPath": "/dA/baf596fa75/profilePhoto/john-smith.jpg",
		"focalPoint": "0.0",
		"path": "b/a/baf596fa-7592-4336-8674-b2ef6d8af748/profilePhoto/john-smith.jpg",
		"isImage": true,
		"idPath": "/dA/f851e34ad1/profilePhoto/john-smith.jpg",
		"size": 2800,
		"name": "john-smith.jpg",
		"width": 0,
		"height": 0
	},
	"host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
	"locked": false,
	"stInode": "045d0b52-fa68-465a-b820-f9fc22febc50",
	"contentType": "BlogAuthor",
	"identifier": "f851e34a-d128-408e-a75a-4fa1c33201b8",
	"firstName": "John",
	"folder": "SYSTEM_FOLDER",
	"hasTitleImage": true,
	"sortOrder": 0,
	"lastName": "Smith",
	"hostName": "demo.dotcms.com",
	"modDate": "2021-06-02 12:38:07.685",
	"title": "John",
	"baseType": "CONTENT",
	"archived": false,
	"working": true,
	"live": true,
	"owner": "036fd43a-6d98-46e0-b22e-bae02cb86f0c",
	"languageId": 1,
	"textFieldMap": "$date",
	"userId": "036fd43a-6d98-46e0-b22e-bae02cb86f0c",
	"url": "/content.baf596fa-7592-4336-8674-b2ef6d8af748",
	"titleImage": "profilePhoto",
	"modUserName": "Admin User",
	"hasLiveVersion": true,
	"modUser": "dotcms.org.1"
}]
...
"blogComment": [{
		"publishDate": "2021-06-18 11:27:18.565",
		"language": {
			"languageId": 1,
			"language": "English",
			"languageCode": "en",
			"country": "United States",
			"countryCode": "US",
			"languageFlag": "en_US",
			"isoCode": "en-us",
			"id": 1
		},
		"body": "new blog comment 1",
		"inode": "0a987cec-6cd1-4530-9fe0-bb74a8860ae3",
		"host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
		"locked": false,
		"stInode": "6044a806-f462-4977-a353-57539eac2a2c",
		"contentType": "BlogComment",
		"identifier": "75e62bcd-294b-4f15-9d37-133c19799a18",
		"folder": "SYSTEM_FOLDER",
		"hasTitleImage": false,
		"sortOrder": 0,
		"hostName": "demo.dotcms.com",
		"modDate": "2021-06-18 11:27:18.565",
		"title": "new blog comment 1",
		"baseType": "CONTENT",
		"archived": false,
		"working": true,
		"live": true,
		"owner": "dotcms.org.1",
		"languageId": 1,
		"url": "/content.c18319c8-cf3f-49c1-86e2-f2c002adb84a",
		"titleImage": "TITLE_IMAGE_NOT_FOUND",
		"modUserName": "Admin User",
		"hasLiveVersion": true,
		"modUser": "dotcms.org.1"
	}
]
```

**Comment by victoralfaro-dotcms** [comment]
With `depth: 1`
```
"author": [{
	"publishDate": "2021-06-02 12:38:07.685",
	"language": {
		"languageId": 1,
		"language": "English",
		"languageCode": "en",
		"country": "United States",
		"countryCode": "US",
		"languageFlag": "en_US",
		"isoCode": "en-us",
		"id": 1
	},
	"inode": "baf596fa-7592-4336-8674-b2ef6d8af748",
	"profilePhoto": {
		"modDate": 1621890340000,
		"sha256": "b1aa20d9c5420987d2503db6eea29074f478e6b63d73dbf6f48f8db39448303b",
		"mime": "image/jpeg",
		"title": "john-smith.jpg",
		"versionPath": "/dA/baf596fa75/profilePhoto/john-smith.jpg",
		"focalPoint": "0.0",
		"path": "b/a/baf596fa-7592-4336-8674-b2ef6d8af748/profilePhoto/john-smith.jpg",
		"isImage": true,
		"idPath": "/dA/f851e34ad1/profilePhoto/john-smith.jpg",
		"size": 2800,
		"name": "john-smith.jpg",
		"width": 0,
		"height": 0
	},
	"host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
	"locked": false,
	"stInode": "045d0b52-fa68-465a-b820-f9fc22febc50",
	"contentType": "BlogAuthor",
	"identifier": "f851e34a-d128-408e-a75a-4fa1c33201b8",
	"firstName": "John",
	"folder": "SYSTEM_FOLDER",
	"hasTitleImage": true,
	"sortOrder": 0,
	"lastName": "Smith",
	"hostName": "demo.dotcms.com",
	"modDate": "2021-06-02 12:38:07.685",
	"title": "John",
	"baseType": "CONTENT",
	"archived": false,
	"working": true,
	"live": true,
	"owner": "036fd43a-6d98-46e0-b22e-bae02cb86f0c",
	"languageId": 1,
	"textFieldMap": "$date",
	"userId": "036fd43a-6d98-46e0-b22e-bae02cb86f0c",
	"url": "/content.baf596fa-7592-4336-8674-b2ef6d8af748",
	"titleImage": "profilePhoto",
	"modUserName": "Admin User",
	"hasLiveVersion": true,
	"modUser": "dotcms.org.1"
}]
...
"blogComment": [{
		"publishDate": "2021-06-18 11:27:18.565",
		"language": {
			"languageId": 1,
			"language": "English",
			"languageCode": "en",
			"country": "United States",
			"countryCode": "US",
			"languageFlag": "en_US",
			"isoCode": "en-us",
			"id": 1
		},
		"body": "new blog comment 1",
		"inode": "0a987cec-6cd1-4530-9fe0-bb74a8860ae3",
		"host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
		"locked": false,
		"stInode": "6044a806-f462-4977-a353-57539eac2a2c",
		"contentType": "BlogComment",
		"identifier": "75e62bcd-294b-4f15-9d37-133c19799a18",
		"folder": "SYSTEM_FOLDER",
		"hasTitleImage": false,
		"sortOrder": 0,
		"hostName": "demo.dotcms.com",
		"modDate": "2021-06-18 11:27:18.565",
		"title": "new blog comment 1",
		"baseType": "CONTENT",
		"archived": false,
		"working": true,
		"live": true,
		"owner": "dotcms.org.1",
		"languageId": 1,
		"url": "/content.c18319c8-cf3f-49c1-86e2-f2c002adb84a",
		"titleImage": "TITLE_IMAGE_NOT_FOUND",
		"modUserName": "Admin User",
		"hasLiveVersion": true,
		"modUser": "dotcms.org.1"
	}
]
```

**Comment by victoralfaro-dotcms** [comment]
With `depth: 2`
```
"blogComment": [{
		"publishDate": "2021-06-18 11:27:18.565",
		"language": {
			"languageId": 1,
			"language": "English",
			"languageCode": "en",
			"country": "United States",
			"countryCode": "US",
			"languageFlag": "en_US",
			"isoCode": "en-us",
			"id": 1
		},
		"body": "new blog comment 1",
		"inode": "0a987cec-6cd1-4530-9fe0-bb74a8860ae3",
		"host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
		"locked": false,
		"stInode": "6044a806-f462-4977-a353-57539eac2a2c",
		"contentType": "BlogComment",
		"identifier": "75e62bcd-294b-4f15-9d37-133c19799a18",
		"folder": "SYSTEM_FOLDER",
		"hasTitleImage": false,
		"sortOrder": 0,
		"hostName": "demo.dotcms.com",
		"modDate": "2021-06-18 11:27:18.565",
		"title": "new blog comment 1",
		"baseType": "CONTENT",
		"archived": false,
		"working": true,
		"live": true,
		"owner": "dotcms.org.1",
		"languageId": 1,
		"url": "/content.c18319c8-cf3f-49c1-86e2-f2c002adb84a",
		"titleImage": "TITLE_IMAGE_NOT_FOUND",
		"modUserName": "Admin User",
		"hasLiveVersion": true,
		"modUser": "dotcms.org.1",
		"commentAuthor": "4150dc1a-92c1-45b8-89ea-6b5c7bdedf74",
		"reply": []
	}
]
```

**Comment by victoralfaro-dotcms** [comment]
With `depth: 3`
```
"blogComment": [{
		"publishDate": "2021-06-18 11:27:18.565",
		"language": {
			"languageId": 1,
			"language": "English",
			"languageCode": "en",
			"country": "United States",
			"countryCode": "US",
			"languageFlag": "en_US",
			"isoCode": "en-us",
			"id": 1
		},
		"body": "new blog comment 1",
		"inode": "0a987cec-6cd1-4530-9fe0-bb74a8860ae3",
		"host": "48190c8c-42c4-46af-8d1a-0cd5db894797",
		"locked": false,
		"stInode": "6044a806-f462-4977-a353-57539eac2a2c",
		"contentType": "BlogComment",
		"identifier": "75e62bcd-294b-4f15-9d37-133c19799a18",
		"folder": "SYSTEM_FOLDER",
		"hasTitleImage": false,
		"sortOrder": 0,
		"hostName": "demo.dotcms.com",
		"modDate": "2021-06-18 11:27:18.565",
		"title": "new blog comment 1",
		"baseType": "CONTENT",
		"archived": false,
		"working": true,
		"live": true,
		"owner": "dotcms.org.1",
		"languageId": 1,
		"url": "/content.c18319c8-cf3f-49c1-86e2-f2c002adb84a",
		"titleImage": "TITLE_IMAGE_NOT_FOUND",
		"modUserName": "Admin User",
		"hasLiveVersion": true,
		"modUser": "dotcms.org.1",
		"commentAuthor": {
			"publishDate": "2021-06-18 11:27:01.32",
			"language": {
				"languageId": 1,
				"language": "English",
				"languageCode": "en",
				"country": "United States",
				"countryCode": "US",
				"languageFlag": "en_US",
				"isoCode": "en-us",
				"id": 1
			},
			"inode": "2310d67d-5f05-4253-b6bf-3c29f8204672",
			"profilePhoto": {},
			"host": "SYSTEM_HOST",
			"locked": false,
			"stInode": "fe719cc1-26d1-499f-8702-c6d35c661286",
			"contentType": "BlogCommentor",
			"identifier": "4150dc1a-92c1-45b8-89ea-6b5c7bdedf74",
			"firstName": "Victor",
			"folder": "SYSTEM_FOLDER",
			"hasTitleImage": false,
			"sortOrder": 0,
			"lastName": "Alfaro",
			"hostName": "System Host",
			"modDate": "2021-06-18 11:27:01.32",
			"title": "Victor",
			"baseType": "CONTENT",
			"archived": false,
			"working": true,
			"live": true,
			"owner": "dotcms.org.1",
			"languageId": 1,
			"url": "/content.2310d67d-5f05-4253-b6bf-3c29f8204672",
			"titleImage": "TITLE_IMAGE_NOT_FOUND",
			"modUserName": "Admin User",
			"hasLiveVersion": true,
			"modUser": "dotcms.org.1"
		},
		"reply": []
	}
]
```

**Comment by victoralfaro-dotcms** [comment]
Without `render: true`
```
"teaser": "$date - From the tame to the exotic, these alternative winter sports will keep you outside and in shape until all the snow"
```
With `render: true`
```
"teaser": "Jun 18, 2021, 12:11:22 PM - From the tame to the exotic, these alternative winter sports will keep you outside and in shape until all the snow"
```

**Pull request merged**
