### PR TITLE
Issue 8414 error when trying to deploy the static plugins on windows

### PR DESCRIPTION
**Pull request by nollymar**
This bug was fixed for Windows platform and additionally tested on Linux. Now, it is possible to execute gradlew deploy-war-tomcat, gradlew create-dist and deploy static plugins (tested with helloworld plugin)

### CODE REVIEW

**Comment by wezell** [comment]
We need a unit test here - this happens all the time.

**Comment by dsilvam** [comment]
@wezell you mean an Integration Test?

**Comment by jtesser** [comment]
maybe the create-dist should fail if the hello-world plugin doesn't deploy @dsilvam

**Comment by wezell** [comment]
Isn't the right fix to add the abstract methods to our AbstractImpls so users don't need to override them?  This has bitten us more than a few times.

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/contentlet/business/ContentletAPIPreHookAbstractImp.java

https://github.com/dotCMS/core/blob/master-3.6/src/com/dotmarketing/portlets/contentlet/business/ContentletAPIPostHookAbstractImp.java

**Pull request merged**
