### PR TITLE
#9892 : Changing the location of the JAMM jar to "/libs/buildlibs/" f…

### PR DESCRIPTION
**Pull request by jcastro-dotcms**
…older. Removing reference to the jar from Artifactory. Adding the repackaged latest version of the JAMM jar.

### CODE REVIEW

**Comment by wezell** [comment]
This looks good but repackage jamm?  Do we need to?

**Comment by jcastro-dotcms** [comment]
@wezell I agree with you. I repackaged the .jar because that's how we had it, but we can use the original version as well.

**Comment by wezell** [comment]
I think for this to be merged into master we ought to update jamm to the latest and un-repackage it.

**Comment by jtesser** [comment]
agreed.

**Review by jgambarios — CHANGES_REQUESTED** [review]
@jcastro-dotcms please check Wills comment: https://github.com/dotCMS/core/pull/9926#issuecomment-252692662

**Comment by jgambarios** [comment]
Closed as the javaagent changed as part of this ticket https://github.com/dotCMS/core/issues/11142

Current agent:
```
-javaagent:$DOTCMS_HOME/WEB-INF/lib/byte-buddy-agent-1.6.12.jar
```

**Pull request closed without merging**
