### PR TITLE
#22255: revert paths in copyDotCmsWebComponents

### PR DESCRIPTION
**Pull request by spbolton**

### CODE REVIEW

**Comment by alfredo-dotcms** [comment]
@spbolton  after copying the files did you clean the extracted directory? so we don't have 2 directories with duplicated files

image

**Review by nollymar — COMMENTED** [review]
@spbolton this PR should target `release-22.06`

**Comment by spbolton** [comment]
> 

No to clean up server impacted by issue I guess we should,  but hate to have a delete in here long term that is for one specific issue.  Will add a delete of the bad folder if it exists and a comment to remove later.

**Comment by spbolton** [comment]
> @spbolton this PR should target `release-22.06`

Ok,  use this PR instead https://github.com/dotCMS/core/pull/22260

**Pull request closed without merging**
