### PR TITLE
Update TempAPI.postman_collection.json

### LINKED ISSUE #27198: Template_Resource.postman_collection.json

### LINKED ISSUE #27260: TempAPI.postman_collection.json

### PR DESCRIPTION
**Pull request by rsh1k**
### Added the following postman test:
* File Size Limit check

image

### CODE REVIEW

**Comment by mbiuki** [comment]
@rashik1144 - are there any more tests being added here?

**Comment by rashik1144** [comment]
> @rashik1144 - are there any more tests being added here?

No

**Comment by AndreyDotcms** [comment]
No issue related to this PR?

**Review by jdotcms — APPROVED** [review]

**Review by AndreyDotcms — APPROVED** [review]

**Comment by mbiuki** [comment]
@bryanboza - is this ready to merge?

**Review by jdotcms — APPROVED** [review]

**Review by nollymar — APPROVED** [review]

**Pull request merged**
