### PR TITLE
Update Scripting_Resource.postman_collection.json

### LINKED ISSUE #27255: Scripting_Resource.postman_collection.json

### PR DESCRIPTION
**Pull request by rsh1k**
### Proposed Changes

Added the following postman tests:

* Test for the existence of file with same name or invalid file

PS: Removed the XSS test as that was not needed in those functions where only admin has access.

### CODE REVIEW

**Comment by rashik1144** [comment]
> In this case we are not validating the text, just the response code (400) In this case the response is: `"message": "The field Host Or Folder is required."` and both tests are in green.
> 
> image
> 
> We need to fix that to validate if the response includes the provided test.
> 
> Also, as a best practice every test should have a separated validation. Is more complex to catch issues when you validate multiple things in the same test. For this we need to add multiple functions, like in the follow case. Example:
> 
> ```
> pm.test("languageCode returned", function () {
>     pm.expect(pm.response.text()).to.include("languageCode");
> });
> 
> pm.test("countryCode returned", function () {
>     pm.expect(pm.response.text()).to.include("countryCode");
> });
> 
> pm.test("language returned", function () {
>     pm.expect(pm.response.text()).to.include("language");
> });
> ```

image

I checked this by commenting the 400 code, it is the message that is being validated.

**Review by fabrizzio-dotCMS — CHANGES_REQUESTED** [review]
Changes on the new test are meant to validate general cases like these: 

Screenshot 2023-12-12 at 08 24 04

Screenshot 2023-12-12 at 08 24 14

All good with that.. however for this test to make sense you should simulate an attack on the original velocity request 

```
{
    "velocity":" #foreach($file in $dotcontent.pull(\"+contentType:FileAsset +metaData.title:*Fear*\",1,\"modDate desc\"))<div id=\"ct\">$file.metaData.contentType</div><div id=\"fileSize\">$file.metaData.fileSize</div><div id=\"modDate\">$file.metaData.modDate</div><div id=\"length\">$file.metaData.length</div><div id=\"isImage\">$file.metaData.isImage</div><div id=\"width\">$file.metaData.width</div><div id=\"height\">$file.metaData.height</div><div id=\"name\">$file.metaData.name</div><div id=\"path\">$file.metaData.path</div><div id=\"sha256\">$file.metaData.sha256</div><div id=\"title\">$file.metaData.title</div>#end "
}
```

And that looks clean. 

I think for such validation to make sense we need to include an attack

**Review by fabrizzio-dotCMS — COMMENTED** [review]
why did you remove the validations? did you try to simulate an attack using the scripting endpoint ? 
Whats the goal of this PR? 
What is it that you're trying to accomplish here?

**Comment by rashik1144** [comment]
> why did you remove the validations? did you try to simulate an attack using the scripting endpoint ? Whats the goal of this PR? What is it that you're trying to accomplish here?

That's removed because this is available only in the admin portal and we decided not to check for XSS there as admin can do whatever changes he/she wants. Now, there is only one change related to the error handling.

**Review by fabrizzio-dotCMS — APPROVED** [review]

**Review by jdotcms — APPROVED** [review]

**Review by nollymar — CHANGES_REQUESTED** [review]
Please fix the broken test

**Comment by mbiuki** [comment]
@rashik1144 - can you fix the problem?

**Comment by rashik1144** [comment]
@nollymar @mbiuki It's fixed now.

**Comment by mbiuki** [comment]
@nollymar @bryanboza please review - ready to merge.

**Review by nollymar — APPROVED** [review]

**Review by mbiuki — APPROVED** [review]

**Pull request merged**
