### PR TITLE
chore: Task Update Java Version to 11.0.23ms in .sdkmanrc (#29377)

### LINKED ISSUE #29377: Task: Update Java Version to 11.0.23-ms in .sdkmanrc
### User Story
As a developer, I need to update the Java version to 11.0.23-ms in our project's environment. This update will involve changing the `.sdkmanrc` file and ensuring that the pull request (PR) successfully passes all checks. The PR should also validate the Java version used in the build process.

### Acceptance Criteria
- The `.sdkmanrc` file is updated to Java version 11.0.23-ms.
- The PR for this change successfully passes all existing checks without requiring internal testing specific to the update.
- The PR includes validation of the Java versions used in the build, ensuring they match the updated version.
- Once validated and merged, relate this issue to the master tracking issue for the Java update and mark as tested.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### dotCMS Version
N/A

### External Links
N/A

### Assumptions & Initiation Needs
- Access to update the `.sdkmanrc` file in the project repository.
- The existing CI/CD pipeline is configured to validate Java versions and run necessary checks on PRs. #27998 

### Quality Assurance Notes & Workarounds
- Separate tracking of the deployment of this Java version through the workflow to monitor any unforeseen issues arising from the Java update itself.

### Sub-Tasks & Estimates
N/A

### PR DESCRIPTION
**Pull request by dcolina**
### Proposed Changes
* Update Java version to `11.0.23-ms` in .sdkmanrc

### Additional Info
Related to #29377 (Task Update Java Version to 11.0.23ms in .sdkmanrc).

This PR fixes: #29377

### CODE REVIEW

**Comment by spbolton** [comment]
A change in the .sdkmanrc file needs to trigger all java workflow steps and any steps using the docker image so we need to update the filters.yml to force this.

**Review by nollymar — APPROVED** [review]

**Review by spbolton — CHANGES_REQUESTED** [review]
I thought that .nvmrc file had already been added, but may be in another PR with the node version change.   I think I had just added the file to both the backend and frontend block rather than create a separate group.  I think the .sdkmanrc and .nvmrc file changes should be grouped together in a group called full_build_test and not specifically for sdkman and then include this group in backend and frontend as well as CLI.  Later we could be more specific for .nvmrc as this generally would only impact core-web and postman but we do not have a specific group for postman at the moment so it is fine that we just run everything for a node version change.  
At the moment we have an .nvmrc file in the root and in core-web/.nvmrc

**Review by dcolina — COMMENTED** [review]
As it was suggested

**Review by dcolina — COMMENTED** [review]
Ready

**Review by spbolton — APPROVED** [review]

**Pull request merged**
