### PR TITLE
fix(db) only alter tables if they require it, as the alter table statement always locks a table

### LINKED ISSUE #28110: Only run startup tasks if they need to be run
### Parent Issue

_No response_

### Task

We are backporting startup tasks that always run `alter table` statements.  We need to only run `alter table` statements if there is something to alter, as I believe they ALWAYS lock the tables they are attempting to alter.

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

_No response_

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

_No response_

### Assumptions & Initiation Needs

_No response_

### Quality Assurance Notes & Workarounds

_No response_

### Sub-Tasks & Estimates

_No response_

### PR DESCRIPTION
**Pull request by wezell**
These UTs were backported, meaning they are running with every restart and might cause table locks.

Added validations to determine if they need to run or not.

ref: #28110

### CODE REVIEW

**Review by erickgonzalez — APPROVED** [review]
Awesome but before merging it, I will review all backported UT task to check if any other missing this.

Assigning this to myself.

**Comment by wezell** [comment]
@erickgonzalez not sure if this was the issue, though we did see the db locked in this.

**Comment by erickgonzalez** [comment]
@wezell found a few more UTs that were backported and always running and added a check to those.

**Review by jdotcms — APPROVED** [review]

**Review by wezell — COMMENTED** [review]
Nice change centralizing the code Eric

**Pull request merged**
